git:
    submodules: true
env:
  global:
      - TMPDIR=/tmp
      - LD_LIBRARY_PATH=$(pwd)/build/lib
      - DYLD_LIBRARY_PATH=$(pwd)/build/lib
branches:
    only:
        - master
sudo: required
os:
    - bionic
language: cpp
before_install:
    - openssl aes-256-cbc -K $encrypted_bea0181439c1_key -iv $encrypted_bea0181439c1_iv -in git_deploy_key.enc -out /tmp/git_deploy_key -d
    - chmod 600 /tmp/git_deploy_key
    - echo 'echo ${SSH_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
    - eval "$(ssh-agent -s)"
    - DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" ssh-add /tmp/git_deploy_key </dev/null
install:
    - ./initPlatform ${TRAVIS_OS_NAME}
script:
    - ./init3rdParty ${TRAVIS_OS_NAME}
    - 
    - ./configure --disable-vera ${LOCAL_BOOST}
    - ls -la build/lib
    - echo ${LD_LIBRARY_PATH}
    - LD_LIBRARY_PATH=$(pwd)/build/lib make
    - ./runTests ${TRAVIS_OS_NAME}
after_success:
    - if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then ./success ${TRAVIS_OS_NAME}; fi

