git:
    submodules: true
branches:
    only:
        - master
sudo: required
os:
    - osx
language: cpp
install:
    - openssl aes-256-cbc -K $encrypted_c6297d5b304c_key -iv $encrypted_c6297d5b304c_iv -in Travis.enc -out ~/.ssh/id_rsa -d
    - chmod 600 ~/.ssh/id_rsa
    - ./initPlatform ${TRAVIS_OS_NAME}
script:
    - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then export LOCAL_BOOST="--with-boost=/tmp/extra"; fi
    - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then export CMAKE_BOOST="-DBOOST_ROOT=/tmp/extra"; fi
    - ./init3rdParty
    - 
    - ./configure ${LOCAL_BOOST}
    - export PATH="${PATH}:$(pwd)/build/bin"
    - export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:$(pwd)/build/lib:/usr/local/lib"
    - export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}:$(pwd)/build/lib:/usr/local/lib"
    - make 
    - benchmark17 Conformance.csv Performance.csv
after_success:
    - if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then ./success ${TRAVIS_OS_NAME}; fi
