#!/bin/bash

if [[ "$1" == "linux" ]]; then
    sudo apt-get update
    sudo apt-get install scons -y
    sudo apt-get install libboost-all-dev
fi
if [[ "$1" == "osx" ]]; then
    export PATH=${PATH}
    brew install scons
    brew install boost
    brew install boost-python
    brew install cmake
    brew install tcl-tk
    for a in /usr/local/lib/libboost_python[0-9][0-9]* ; do
        sudo ln -s ${a} ${a/[0-9][0-9]/}
    done
fi

