#!/bin/bash

CWD=$(pwd)

export PATH="${PATH}:$(pwd)/build/bin"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:$(pwd)/build/lib:/usr/local/lib:${CWD}/thirdparty/ThorsSerializer/build/lib/:/opt/homebrew/lib/"
export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}:$(pwd)/build/lib:/usr/local/lib:${CWD}/thirdparty/ThorsSerializer/build/lib/:/opt/homebrew/lib/"

export parser=$1
export filter=$2
export flags=$3

benchmark --append --filter=${filter} --parser=${parser} ${flags} Conformance.csv Performance.csv


