#!/bin/bash

CWD=$(pwd)

export PATH="${PATH}:$(pwd)/build/bin"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:$(pwd)/build/lib:/usr/local/lib:${CWD}/thirdparty/ThorsSerializer/build/lib/:/opt/homebrew/lib/"
export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}:$(pwd)/build/lib:/usr/local/lib:${CWD}/thirdparty/ThorsSerializer/build/lib/:/opt/homebrew/lib/"

export parser=NewProject
export filters=$1
export flags=$2

if [[ ${filters} == "" ]]; then
    filters=$(benchmark --listTests)
fi

for filter in ${filters}; do
    benchmark --append --filter=${filter} --parser=${parser} ${flags} Conformance.csv Performance.csv
done


