#!/bin/bash

if [[ "$1" == "linux" ]]; then
    sudo apt-get install node.js
fi
token=${GH_TOKEN}
if [[ "${token}" != "" ]]; then
    echo "--- Have Token ---"
    token="${token}@"
else
    echo "--- NO TOKEN ---"
fi

git clone https://${token}github.com/Loki-Astari/geeky-nextjs

cp Conformance.csv geeky-nextjs/public/Json/raw/Conformance.$1.csv
cp Performance.csv geeky-nextjs/public/Json/raw/Performance.$1.csv

if [[ "$1" == "OSX" ]]; then
    php ./script/stats.php       Stats.csv          > loki-astari.github.io/source/Json/raw.Stats.csv
fi

cd geeky-nextjs
git config --global user.email "Loki.Astari@gmail.com"
git config --global user.name "Loki Astari"
git commit -a -m "Update $1 Files"
git push https://${token}github.com/Loki-Astari/geeky-nextjs


# Push back to github.

