#!/bin/bash

github=$1

name=${github##*/}
name=${name%.git}
name=${name/-/}
name=${name/#/}


echo "From:     ${github}"
echo "Name:     ${name}"

echo "Good?"
read alternativeName

if [[ ${alternativeName} != "" ]]; then
    name=${alternativeName}
fi

echo
echo 1
git branch Add${name}
echo
echo 2
git push origin Add${name}
echo
echo 3
git branch -d Add${name}
echo
echo 4
git checkout Add${name}

echo
echo 5
git submodule add ${github}  thirdparty/${name}
echo
echo 6
git mv init/NewProject  init/${name}
echo
echo 7
git mv src/ThirdParty/NewProjectTest.cpp src/ThirdParty/${name}Test.cpp

sed -i '' -e "s/NewProject/${name}/" src/ThirdParty/${name}Test.cpp
sed -i '' -e "s/NewProject/${name}/" src/ThirdParty/Makefile
sed -i '' -e "s/NewProject/${name}/" src/ThirdParty/test.cpp
sed -i '' -e "s/NewProject/${name}/" runOneTest

echo
echo 8
git add src/ThirdParty/${name}Test.cpp src/ThirdParty/Makefile src/ThirdParty/test.cpp runOneTest


